name: "RN Test Lint - CI"
description: "install, test and lint, using yarn"
runs:
  using: "composite"

  steps:
    - name: Install dependencies
      run: yarn
      shell: bash

    - name: Lint
      run: yarn lint
      shell: bash

    - name: Test
      run: yarn test
      shell: bash
