name: "RN Test Lint - CI"
description: "install, test and lint, using yarn"
runs:
  using: "composite"

  steps:
    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test
